# Generated by Django 5.0.6 on 2024-06-24 21:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(default='8-800-555-3535', verbose_name='Номер телефона')),
                ('email', models.EmailField(default='admin@admin.com', max_length=254, verbose_name='Электронная почта')),
                ('telegram', models.CharField(default='@admin', verbose_name='Телеграм')),
                ('user_agreement_link', models.URLField(default='', verbose_name='Ссылка на пользовательское соглашение')),
                ('privacy_policy_link', models.URLField(default='', verbose_name='Ссылка на политику конфиденциальности')),
                ('about_us', models.TextField(default='about us', verbose_name='О нас')),
                ('why_us', models.TextField(default='Why us specifically', verbose_name='Почему именно мы')),
            ],
            options={
                'verbose_name': 'Настройка главной страницы',
                'verbose_name_plural': 'Настрийки главной страницы',
            },
        ),
    ]
