# Generated by Django 5.0.8 on 2024-09-02 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('post', models.CharField(max_length=256, verbose_name='Должность')),
                ('telegram', models.URLField(max_length=256, verbose_name='Ссылка на телеграм')),
                ('photo', models.ImageField(upload_to='site_settings/about_us/photo', verbose_name='Фото сотрудника')),
            ],
            options={
                'verbose_name': 'О нас',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=24, verbose_name='Номер телефона')),
                ('telegram', models.URLField(max_length=256, verbose_name='Телеграм')),
                ('email', models.EmailField(max_length=256, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Messangers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instagram', models.URLField(max_length=256, verbose_name='Инстаграм')),
                ('vk', models.URLField(max_length=256, verbose_name='Вконтакте')),
                ('telegram', models.URLField(max_length=256, verbose_name='Телеграм')),
                ('whatsapp', models.URLField(max_length=256, verbose_name='Ватсап')),
            ],
            options={
                'verbose_name': 'Мессенджер',
                'verbose_name_plural': 'Мессенджеры',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('how_much_done', models.PositiveIntegerField(verbose_name='Сколько сделано')),
                ('what_done', models.CharField(max_length=256, verbose_name='Что сделано')),
            ],
            options={
                'verbose_name': 'Статистика',
            },
        ),
        migrations.DeleteModel(
            name='MainPageSettings',
        ),
    ]
