# Generated by Django 5.0.6 on 2024-05-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagesettings',
            name='about_us',
            field=models.TextField(default='about us', verbose_name='О нас'),
        ),
        migrations.AlterField(
            model_name='mainpagesettings',
            name='email',
            field=models.EmailField(default='admin@admin.com', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='mainpagesettings',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='mainpagesettings',
            name='privacy_policy_link',
            field=models.URLField(default='', verbose_name='Ссылка на политику конфиденциальности'),
        ),
        migrations.AlterField(
            model_name='mainpagesettings',
            name='telegram',
            field=models.CharField(default='@admin', verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='mainpagesettings',
            name='user_agreement_link',
            field=models.URLField(default='', verbose_name='Ссылка на пользовательское соглашение'),
        ),
        migrations.AlterField(
            model_name='mainpagesettings',
            name='why_us',
            field=models.TextField(default='Why us specifically', verbose_name='Почему именно мы'),
        ),
    ]
