# Generated by Django 5.0.8 on 2024-09-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_aboutus_contact_messangers_stat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ('created',), 'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
    ]
