# Generated by Django 5.0.6 on 2024-05-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_mainpagesettings_about_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagesettings',
            name='number',
            field=models.CharField(default='8-800-555-3535', verbose_name='Номер телефона'),
        ),
    ]
