# Generated by Django 5.1 on 2024-09-24 12:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_aboutus_options_alter_stat_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCustomers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('company', models.CharField(max_length=256, verbose_name='Компания')),
                ('logo', models.ImageField(upload_to='site_settings/favourite_customers/logo', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Любимый пользователь',
                'verbose_name_plural': 'Любимые пользователи',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('company', models.CharField(max_length=256, verbose_name='Компания')),
                ('post', models.CharField(max_length=256, verbose_name='Должность')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('review', models.TextField(max_length=4096, verbose_name='Отзыв')),
                ('logo', models.ImageField(upload_to='site_settings/reviews/logo', verbose_name='Логотип')),
                ('photo', models.ImageField(upload_to='site_settings/reviews/photo', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('created',),
            },
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ('created',), 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='lastname',
            field=models.CharField(default='Ivanov', max_length=256, verbose_name='Фамилия сотрудника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='name',
            field=models.CharField(default='Ivan', max_length=256, verbose_name='Имя сотрудника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='telegram',
            field=models.CharField(max_length=256, verbose_name='Ссылка на телеграм'),
        ),
    ]
