# Generated by Django 5.0.6 on 2024-05-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('post', models.CharField(max_length=256, verbose_name='Должность')),
                ('description', models.TextField(max_length=512, verbose_name='Описание вакансии')),
                ('salary_fork', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплатная вилка')),
                ('image', models.ImageField(upload_to='vacancies/image', verbose_name='Фотография вакансии')),
            ],
        ),
    ]
