# Generated by Django 5.0.6 on 2024-05-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('number', models.IntegerField(max_length=15, verbose_name='Номер')),
                ('link', models.URLField(verbose_name='Ссылка на социальную сеть')),
                ('file', models.FileField(upload_to='vacancies/files', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Форма вакансии',
                'verbose_name_plural': 'Формы вакансий',
            },
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
