# Generated by Django 5.0.6 on 2024-05-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancyform_alter_vacancy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyform',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='vacancies/files', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='vacancyform',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на социальную сеть'),
        ),
    ]
