export const reviews = {
  total: '31',
  reviews: [
    {
      id: 1,
      text: 'Скоро год, как сотрудничаем с компанией. Начали работать с самого начала нашего бизнеса. Ребята достаточно быстро и качественно создали группу, разработав для нее логотип, аватарку, определенный фирменный стиль магазина.',
      author: 'Анастасия Иванова',
      img: '/img/manager_1.png',
      position: 'Директор по рекламе',
      label: '/img/label_1.png',
    },
    {
      id: 2,
      text: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Saepe fugiat delectus minima et placeat adipisci necessitatibus voluptates illum quos, expedita quaerat deleniti quod aperiam ipsum assumenda neque itaque ducimus repellendus, vel magnam quasi at officia debitis? Suscipit, alias. Adipisci, doloribus.',
      author: 'Мария',
      img: '/img/manager_2.jpg',
      position: 'Менеджер',
      label: '/img/label_1.png',
    },
    {
      id: 3,
      text: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Saepe fugiat delectus minima et placeat adipisci necessitatibus voluptates illum quos, expedita quaerat deleniti quod aperiam ipsum assumenda neque itaque ducimus repellendus, vel magnam quasi at officia debitis? Suscipit, alias. Adipisci, doloribus.',
      author: 'Мария',
      img: '/img/manager_2.jpg',
      position: 'Менеджер',
      label: '/img/label_1.png',
    },
    {
      id: 4,
      text: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Saepe fugiat delectus minima et placeat adipisci necessitatibus voluptates illum quos, expedita quaerat deleniti quod aperiam ipsum assumenda neque itaque ducimus repellendus, vel magnam quasi at officia debitis? Suscipit, alias. Adipisci, doloribus.',
      author: 'Мария',
      img: '/img/manager_2.jpg',
      position: 'Менеджер',
      label: '/img/label_1.png',
    },
    {
      id: 5,
      text: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Saepe fugiat delectus minima et placeat adipisci necessitatibus voluptates illum quos, expedita quaerat deleniti quod aperiam ipsum assumenda neque itaque ducimus repellendus, vel magnam quasi at officia debitis? Suscipit, alias. Adipisci, doloribus.',
      author: 'Мария',
      img: '/img/manager_2.jpg',
      position: 'Менеджер',
      label: '/img/label_1.png',
    },
    {
      id: 6,
      text: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Saepe fugiat delectus minima et placeat adipisci necessitatibus voluptates illum quos, expedita quaerat deleniti quod aperiam ipsum assumenda neque itaque ducimus repellendus, vel magnam quasi at officia debitis? Suscipit, alias. Adipisci, doloribus.',
      author: 'Мария',
      img: '/img/manager_2.jpg',
      position: 'Менеджер',
      label: '/img/label_1.png',
    },
    {
      id: 7,
      text: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Saepe fugiat delectus minima et placeat adipisci necessitatibus voluptates illum quos, expedita quaerat deleniti quod aperiam ipsum assumenda neque itaque ducimus repellendus, vel magnam quasi at officia debitis? Suscipit, alias. Adipisci, doloribus.',
      author: 'Мария',
      img: '/img/manager_2.jpg',
      position: 'Менеджер',
      label: '/img/label_1.png',
    },

  ],
}
