# Generated by Django 5.1 on 2024-09-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='gif',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='solved_problems',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='team',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='video',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(default='inc', max_length=256, verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='decision',
            field=models.TextField(default='decision', max_length=4096, verbose_name='Решение кейса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='task',
            field=models.TextField(default='task', max_length=4096, verbose_name='Задача кейса'),
            preserve_default=False,
        ),
    ]
