# Generated by Django 5.0.2 on 2024-05-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('post', models.CharField(max_length=256, verbose_name='Должность')),
                ('description', models.TextField(max_length=512, verbose_name='Описание вакансии')),
                ('salary_fork', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплатная вилка')),
                ('image', models.ImageField(upload_to='vacancies/image', verbose_name='Фотография вакансии')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='VacancyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на социальную сеть')),
                ('file', models.FileField(blank=True, null=True, upload_to='vacancies/files', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Форма вакансии',
                'verbose_name_plural': 'Формы вакансий',
            },
        ),
    ]
