# Generated by Django 5.0.6 on 2024-05-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ('title',), 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterModelOptions(
            name='vacancyform',
            options={'ordering': ('name',), 'verbose_name': 'Форма вакансии', 'verbose_name_plural': 'Формы вакансий'},
        ),
    ]
