# Generated by Django 5.0.6 on 2024-06-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyform',
            name='number',
        ),
        migrations.AddField(
            model_name='vacancyform',
            name='email',
            field=models.EmailField(default='default@default.com', max_length=254, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
    ]
