# Generated by Django 5.0.7 on 2024-07-09 15:07

import apps.utils.models_mixins.models_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyform',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.utils.models_mixins.models_mixins.file_directory_path, verbose_name='Файл'),
        ),
    ]
