# Generated by Django 5.0.6 on 2024-05-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_fork',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_fork_gt',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Верхняя граница зарлатной вилки'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_fork_lt',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Нижняя граница зарлатной вилки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='Описание вакансии'),
        ),
    ]
