# Generated by Django 5.0.6 on 2024-06-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceblock',
            options={'ordering': ('created',), 'verbose_name': 'Блок услуги', 'verbose_name_plural': 'Блоки услуг'},
        ),
    ]
