# Generated by Django 5.0.6 on 2024-06-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на социальную сеть')),
                ('file', models.FileField(blank=True, null=True, upload_to='vacancies/files', verbose_name='Файл')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Обратная  связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
