# Generated by Django 5.0.6 on 2024-06-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная  связь', 'verbose_name_plural': 'Обратная связь'},
        ),
    ]
