# Generated by Django 5.0.6 on 2024-06-24 21:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=256, verbose_name='Название новости')),
                ('description', models.TextField(max_length=1024, verbose_name='Краткое описание новости')),
                ('photo', models.ImageField(upload_to='news/photo/', verbose_name='Фото новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BlockOfNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Название блока новости')),
                ('text', models.TextField(verbose_name='Текст блока новости')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_of_news', to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Блок новости',
                'verbose_name_plural': 'Блоки новостей',
                'ordering': ('name',),
            },
        ),
    ]
