# Generated by Django 5.0.6 on 2024-05-27 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockofnews',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_of_news', to='news.news', verbose_name='Новость'),
        ),
    ]
