# Generated by Django 5.0.6 on 2024-05-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_blockofnews_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockofnews',
            options={'ordering': ('name',), 'verbose_name': 'Блок новости', 'verbose_name_plural': 'Блоки новостей'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('content_type',), 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('name',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
