# Generated by Django 5.0.6 on 2024-06-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_blockofnews_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
