# Generated by Django 5.0.6 on 2024-06-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='amenities/GIF/', verbose_name='GIF услуги'),
        ),
        migrations.AddField(
            model_name='amenities',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='amenities/video/', verbose_name='Видео услуги'),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='photo',
            field=models.ImageField(upload_to='amenities/photo/', verbose_name='Фото услуги'),
        ),
    ]
