# Generated by Django 5.1.5 on 2025-01-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0003_amenities_text_and_label_color_skill_technology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Уникальная ссылка на телеграм'),
        ),
    ]
