# Generated by Django 5.1.5 on 2025-01-25 18:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0004_amenities_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostPopularQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('title', models.CharField(max_length=256, verbose_name='Вопрос')),
                ('description', models.CharField(max_length=2048, verbose_name='Ответ на вопрос')),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_of_amenities', to='amenities.amenities', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Скилл',
                'verbose_name_plural': 'Скиллы',
                'ordering': ('created',),
            },
        ),
    ]
